---
- name: copy file in docker node
  hosts: dockernode
  become: true
  gather_facts: no


  tasks:
  - name: copy a file
    copy:
     src: /home/ansadmin/index.html
     dest: /var/www/html
     mode: 0666
