---
- name: create a file ana directory in docker node
  hosts: dockernode
  become: true
  gather_facts: no


  tasks:
  - name: creating a file 
    file:
     path: /opt/index.yml
     state: touch
     mode: 0777
     owner: biks

  - name: creating a directory
    file:
     path: /opt/demo_dir
     state: absent
   
