---
- name: install appache/httpd
  hosts: dockernode
  become: true
  
  tasks:
  - name: install htppd
    yum:
     name: httpd
     state: installed
    notify: start httpd
     
  handlers: 
  - name: start httpd
    service:
     name: httpd
     state: started
