---
- name: install appache/httpd
  hosts: dockernode
  become: true
  
  tasks:
  - name: install htppd
    yum:
     name: httpd
     state: installed
     
  - name: start service
    service:
     name: httpd
     state: started
