---
- name: install appache/httpd
  hosts: dockernode
  become: true
  vars: 
   port: 8081

  tasks: 
  - name: install htppd
    yum: 
     name: httpd
     state: installed
    notify: start httpd
  - name: Ensure port should be {{ port }}
    lineinfile: 
     path: /etc/httpd/conf/httpd.conf
     regexp: '^Listen'
     insertafter: '^#Listen'
     line: Listen {{ port }}
    notify: restart httpd
    
  - name: copy a file
    copy:
     src: /home/ansadmin/index.html
     dest: /var/www/html
    notify: restart httpd

  handlers:
  - name: start httpd
    service:
     name: httpd
     state: started
  - name: restart httpd
    service: 
     name: httpd
     state: restarted 
     
     
